# YAML SCRIPT: 
# Phiên bản hiện tại: 1.0.0.0
# Lịch sử và nguyên nhân chỉnh sửa:
# - 1.0.0.0: 
# NOTE: tên file script thực tế nên là script.yaml, example.yaml chỉ để minh họa và để tránh xung đột tên file.

script:
  mes_defect_code:
    DOWNLOAD_K81_FIRMWARE_FAIL : UN01
    DOWNLOAD_K81_APP_FAIL : UN02
  test_environments: ~
  test_configurations: 
    - &t650c_configuration
      flags: ~
      script_information: 
        station_name: "T650C K81 DOWNLOAD" 
        description: "T650C"
      script_configuration:
        general: ~
        fixture_configuration: ~

  test_sequences: 
    - &t650c_test_sequence
      test_items:
        - name: CHECK_MBS_NO
          steps: 
            - do: mes.CHECK_MBS_NO
              with: ~
              on_success: ~
              on_fail: ~

        - name: MES_GET_ETH_MAC
          steps: 
            - do: mes.GET_MAC_LIST
              with: ~
              on_success: ~
              on_fail: ~

        - name: PMS_AUTO_TEST
          steps: 
            - do: pms.AUTO
              with:
                working_path: C:\\T650C_SA_K81DL_TOOL20230929\\V1.21.2\PMS_Simulation_Window_V1.09
                exe_name: PMS_Simulation_Window_V1.09.exe
                bt_mac: ~
                wifi_mac: ~
                eth_mac: 123456789012 #$context MES[mac]
              on_success: ~
              on_fail: ~

        - name: MT_AUTO_TEST
          steps: 
            - do: mt.AUTO
              with: 
                working_path: C:\T650C_SA_K81DL_TOOL20230929\V1.21.2
                exe_name: PCBA_tests.exe
                ict_sn_01: $context input_str
                ict_sn_02: ~
              on_success: ~
              on_fail: ~

        - name: CHECK_RESULT
          steps: 
            - do: mt.check_tasklist
              with: 
                board_id: 01
                expect: K81-Firmware,Complete
              on_success: 
                - do: return.continue
              on_fail: 
                - do: return.FAIL
                  with:
                    error_code: DOWNLOAD_K81_FIRMWARE_FAIL
            
            - do: mt.check_tasklist
              with: 
                board_id: 01
                expect: K81-APP,Complete
              on_success: 
                - do: return.continue
              on_fail: 
                - do: return.FAIL
                  with:
                    error_code: DOWNLOAD_K81_APP_FAIL
                      
  test_targets: 
    - model_id: VN6501AACAMB
      environment: ~
      test_config: *t650c_configuration 
      test_sequence: *t650c_test_sequence 


